spring.application.name=Real-time-Task-Management

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis (match Railway variable names exactly)
spring.data.redis.host=${REDISHOST}
spring.data.redis.port=${REDISPORT}
spring.data.redis.username=${REDISUSER}
spring.data.redis.password=${REDISPASSWORD}
spring.cache.type=redis

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security
spring.security.enabled=true

# Server
server.port=${PORT:8080}

# OAuth2 GitHub Login
spring.security.oauth2.client.registration.github.client-id=Ov23liSphyOMS46T9CD2
spring.security.oauth2.client.registration.github.client-secret=815248cf87fa77ae9bb31499889db5f33d0c33cf
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.github.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.github.client-name=GitHub

spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id
